// default package
// Generated 29-abr-2012 19:07:22 by Hibernate Tools 3.4.0.CR1



/**
 * RankingsId generated by hbm2java
 */
public class RankingsId  implements java.io.Serializable {


     private String username;
     private String game;

    public RankingsId() {
    }

    public RankingsId(String username, String game) {
       this.username = username;
       this.game = game;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getGame() {
        return this.game;
    }
    
    public void setGame(String game) {
        this.game = game;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RankingsId) ) return false;
		 RankingsId castOther = ( RankingsId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getGame()==castOther.getGame()) || ( this.getGame()!=null && castOther.getGame()!=null && this.getGame().equals(castOther.getGame()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getGame() == null ? 0 : this.getGame().hashCode() );
         return result;
   }   


}


