// default package
// Generated 29-abr-2012 19:07:22 by Hibernate Tools 3.4.0.CR1



/**
 * Friends generated by hbm2java
 */
public class Friends  implements java.io.Serializable {


     private FriendsId id;

    public Friends() {
    }

    public Friends(FriendsId id) {
       this.id = id;
    }
   
    public FriendsId getId() {
        return this.id;
    }
    
    public void setId(FriendsId id) {
        this.id = id;
    }




}


