// default package
// Generated 29-abr-2012 19:07:22 by Hibernate Tools 3.4.0.CR1



/**
 * FriendsId generated by hbm2java
 */
public class FriendsId  implements java.io.Serializable {


     private String username;
     private String friend;

    public FriendsId() {
    }

    public FriendsId(String username, String friend) {
       this.username = username;
       this.friend = friend;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFriend() {
        return this.friend;
    }
    
    public void setFriend(String friend) {
        this.friend = friend;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendsId) ) return false;
		 FriendsId castOther = ( FriendsId ) other; 
         
		 return ( (this.getUsername()==castOther.getUsername()) || ( this.getUsername()!=null && castOther.getUsername()!=null && this.getUsername().equals(castOther.getUsername()) ) )
 && ( (this.getFriend()==castOther.getFriend()) || ( this.getFriend()!=null && castOther.getFriend()!=null && this.getFriend().equals(castOther.getFriend()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsername() == null ? 0 : this.getUsername().hashCode() );
         result = 37 * result + ( getFriend() == null ? 0 : this.getFriend().hashCode() );
         return result;
   }   


}


