// default package
// Generated 29-abr-2012 19:07:22 by Hibernate Tools 3.4.0.CR1



/**
 * Rankings generated by hbm2java
 */
public class Rankings  implements java.io.Serializable {


     private RankingsId id;
     private int wonGames;
     private int lostGames;

    public Rankings() {
    }

    public Rankings(RankingsId id, int wonGames, int lostGames) {
       this.id = id;
       this.wonGames = wonGames;
       this.lostGames = lostGames;
    }
   
    public RankingsId getId() {
        return this.id;
    }
    
    public void setId(RankingsId id) {
        this.id = id;
    }
    public int getWonGames() {
        return this.wonGames;
    }
    
    public void setWonGames(int wonGames) {
        this.wonGames = wonGames;
    }
    public int getLostGames() {
        return this.lostGames;
    }
    
    public void setLostGames(int lostGames) {
        this.lostGames = lostGames;
    }




}


