// default package
// Generated 29-abr-2012 19:07:22 by Hibernate Tools 3.4.0.CR1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String password;
     private String email;
     private String role;
     private String name;
     private String lastName;
     private String secondLastName;

    public User() {
    }

	
    public User(String username, String password, String email, String role) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = role;
    }
    public User(String username, String password, String email, String role, String name, String lastName, String secondLastName) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.role = role;
       this.name = name;
       this.lastName = lastName;
       this.secondLastName = secondLastName;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getSecondLastName() {
        return this.secondLastName;
    }
    
    public void setSecondLastName(String secondLastName) {
        this.secondLastName = secondLastName;
    }




}


